<?php


use Phinx\Seed\AbstractSeed;

class PlansSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run()
    {
        $plans = [
            [
                "NAME" => "Premier Plus",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Elite",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Ultimate Care",
                "region_id" => 12,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 7,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 7,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 7,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Access VIP",
                "region_id" => 7,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Optimum VIP",
                "region_id" => 7,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Senior VIP",
                "region_id" => 7,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Critical Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Select",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Premier",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Elite",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Ultimate",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Flex 1",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Flex 2",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Diamond Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Complete Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Advantage Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Secure Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Essential Care",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 0,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Major Medical",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Mundial",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice II Mundial",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Mundial",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Latam",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice II Latam",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Latam",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Elite",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 17,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 17,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 17,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 18,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Access VIP",
                "region_id" => 19,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 20,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 20,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 11,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 11,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 16,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 16,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 16,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 16,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 21,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 21,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 21,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 21,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 22,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 22,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 22,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 22,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 11,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 23,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 23,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 23,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 6,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 6,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Special VIP",
                "region_id" => 24,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Universal VIP",
                "region_id" => 24,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 6,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Absolute VIP",
                "region_id" => 24,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Latam",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice II Latam",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 9,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Advance Care",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Prime Care",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 13,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 10,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 13,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 13,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "IDEAL 500",
                "region_id" => 25,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Meridian II Guarantee",
                "region_id" => 25,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Azure Guarantee",
                "region_id" => 25,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Latam",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Mundial",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice II Mundial",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Mundial",
                "region_id" => 3,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Premier Plus",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 10,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 10,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Global",
                "region_id" => 26,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Care",
                "region_id" => 26,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Care Latam",
                "region_id" => 26,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Select",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Select",
                "region_id" => 26,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Select",
                "region_id" => 22,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Medical Select",
                "region_id" => 8,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Mundial (Sin dental)",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Mundial (Sin dental)",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Choice I Latam (Sin dental)",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Pass Connect Latam (Sin dental)",
                "region_id" => 1,
                "joint" => 1,
                "enabled" => 1,
                "quote_type" => "New",
            ],
            [
                "NAME" => "Global Elite (R)",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "Renovation",
            ],
            [
                "NAME" => "Global Premier (R)",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "Renovation",
            ],
            [
                "NAME" => "Global Select (R)",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "Renovation",
            ],
            [
                "NAME" => "Global Major Medical (R)",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "Renovation",
            ],
            [
                "NAME" => "Global Ultimate (R)",
                "region_id" => 15,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "Renovation",
            ],
            [
                "NAME" => "Premier Care",
                "region_id" => 12,
                "joint" => 0,
                "enabled" => 1,
                "quote_type" => "New",
            ],
        ];

        $table = $this->table('plans');
        $table->insert($plans)->saveData();


    }

    public function getDependencies(){
        return [
            'PlanNamesSeeder',
            'RegionsSeeder',
            'CompaniesSeeder'
        ];
    }
}
