version: 2.1
commands:
  copy_files:
    parameters:
      source:
        type: string
      destination:
        type: string
    steps:
      - run: rsync -avce "ssh -o StrictHostKeyChecking=no" --delete --exclude ".htaccess" << parameters.source >> $SSH_USER@$SSH_HOST:<< parameters.destination >>
  set_up_server:
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "55:17:29:55:00:df:f5:9a:2d:d8:36:d5:31:4a:26:43"
      - checkout
      - run: sudo apt install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
jobs:
  create_production_build:
    docker:
      - image: circleci/php:7.3.1-node-browsers
    steps:
      - set_up_server
      - copy_files:
          source: /home/circleci/project/
          destination: /home/megabrokers/public_html/quoti/api
  create_test_build:
    docker:
      - image: circleci/php:7.3.1-node-browsers
    steps:
      - set_up_server
      - copy_files:
          source: /home/circleci/project/
          destination: /home/megabrokers/public_html/test/quoti/api
workflows:
  version: 2
  deploy:
    jobs:
      - create_production_build:
          filters:
            branches:
              only:
                - master
      - create_test_build:
        filters:
          branches:
            only:
              - develop
